# Generated by Django 5.2.7 on 2025-10-17 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('plan_type', models.CharField(choices=[('professor', 'Plano Professor'), ('institucional', 'Plano Institucional')], max_length=20, verbose_name='Tipo de Plano')),
                ('billing_period', models.CharField(choices=[('monthly', 'Mensal'), ('semester', 'Semestral'), ('annual', 'Anual')], max_length=20, verbose_name='Período de Cobrança')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Product ID')),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Price ID')),
                ('max_classes', models.IntegerField(blank=True, help_text='Deixe em branco para ilimitado', null=True, verbose_name='Máximo de Turmas')),
                ('extra_class_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço por Turma Extra')),
                ('personalized_question_bank', models.BooleanField(default=True, verbose_name='Banco de Questões Personalizado')),
                ('max_test_versions', models.IntegerField(default=5, verbose_name='Máximo de Versões de Simulado')),
                ('automatic_correction', models.BooleanField(default=True, verbose_name='Correção Automática')),
                ('performance_dashboard', models.BooleanField(default=True, verbose_name='Dashboard de Desempenho')),
                ('custom_student_app', models.BooleanField(default=False, verbose_name='App Personalizado do Aluno')),
                ('advanced_reports', models.BooleanField(default=False, verbose_name='Relatórios Avançados')),
                ('priority_support', models.BooleanField(default=False, verbose_name='Suporte Prioritário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mais Popular')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento Webhook Stripe',
                'verbose_name_plural': 'Eventos Webhook Stripe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Stripe Subscription ID')),
                ('stripe_customer_id', models.CharField(max_length=255, verbose_name='Stripe Customer ID')),
                ('status', models.CharField(choices=[('incomplete', 'Incompleta'), ('incomplete_expired', 'Incompleta Expirada'), ('trialing', 'Em Período de Teste'), ('active', 'Ativa'), ('past_due', 'Vencida'), ('canceled', 'Cancelada'), ('unpaid', 'Não Paga')], default='incomplete', max_length=20, verbose_name='Status')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Início do Período Atual')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Período Atual')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Cancelar no Fim do Período')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada em')),
                ('extra_classes', models.IntegerField(default=0, verbose_name='Turmas Extras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Stripe Payment Intent ID')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Invoice ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Charge ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='Moeda')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('succeeded', 'Sucesso'), ('failed', 'Falhou'), ('refunded', 'Reembolsado')], max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.subscription')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
