# Generated by Django 5.0.7 on 2024-11-18 01:35

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('conteudo', models.CharField(max_length=100)),
                ('enunciado', ckeditor.fields.RichTextField()),
                ('imagem', models.ImageField(blank=True, help_text='Imagens devem ter no máximo 5MB', null=True, upload_to='questoes/')),
                ('alternativa_a', ckeditor.fields.RichTextField()),
                ('alternativa_b', ckeditor.fields.RichTextField()),
                ('alternativa_c', ckeditor.fields.RichTextField()),
                ('alternativa_d', ckeditor.fields.RichTextField()),
                ('alternativa_e', ckeditor.fields.RichTextField()),
                ('resposta_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('nivel_dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], default='M', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacao', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacao', models.DateTimeField(auto_now=True)),
                ('cabecalho', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('instrucoes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulados', to=settings.AUTH_USER_MODEL)),
                ('questoes', models.ManyToManyField(related_name='simulados', through='questions.QuestaoSimulado', to='questions.questao')),
            ],
            options={
                'verbose_name': 'Simulado',
                'verbose_name_plural': 'Simulados',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='questaosimulado',
            name='simulado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.simulado'),
        ),
        migrations.AlterUniqueTogether(
            name='questaosimulado',
            unique_together={('simulado', 'ordem'), ('simulado', 'questao')},
        ),
    ]
