# Generated by Django 5.1.3 on 2024-11-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='simulados', to='classes.class'),
        ),
    ]
