# Generated by Django 5.2 on 2025-05-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_simulado_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='gabaritos_gerados',
            field=models.JSONField(blank=True, help_text='Armazena as informações de embaralhamento após gerar o PDF', null=True),
        ),
    ]
