# Generated by Django 5.2.1 on 2025-06-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_alter_simulado_gabaritos_gerados_resultado_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="resultado",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="resultado",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="resultado",
            name="simulado",
        ),
        migrations.RemoveField(
            model_name="resultado",
            name="versao_gabarito",
        ),
        migrations.RemoveField(
            model_name="versaogabarito",
            name="simulado",
        ),
        migrations.RemoveField(
            model_name="versaogabarito",
            name="usuario_geracao",
        ),
        migrations.RemoveField(
            model_name="simulado",
            name="versao_gabarito_oficial",
        ),
        migrations.AlterField(
            model_name="simulado",
            name="gabaritos_gerados",
            field=models.JSONField(
                blank=True,
                help_text="Armazena as informações de embaralhamento após gerar o PDF",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="DetalhesResposta",
        ),
        migrations.DeleteModel(
            name="Resultado",
        ),
        migrations.DeleteModel(
            name="VersaoGabarito",
        ),
    ]
