# Generated by Django 5.2.1 on 2025-07-01 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0004_studentperformance_versao"),
        ("questions", "0009_alter_resultado_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulado",
            name="gabaritos_gerados",
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pontuacao", models.FloatField()),
                ("total_questoes", models.IntegerField()),
                ("acertos", models.IntegerField()),
                ("data_correcao", models.DateTimeField(auto_now_add=True)),
                ("versao", models.CharField(blank=True, max_length=20, null=True)),
                ("tipo_prova", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions_resultados",
                        to="classes.student",
                    ),
                ),
                (
                    "simulado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions_resultados",
                        to="questions.simulado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado",
                "verbose_name_plural": "Resultados",
                "ordering": ["-data_correcao"],
            },
        ),
        migrations.CreateModel(
            name="DetalhesResposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.CharField(max_length=10)),
                ("resposta_aluno", models.CharField(max_length=1)),
                ("resposta_correta", models.CharField(max_length=1)),
                ("acertou", models.BooleanField(default=False)),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions_detalhes_resposta",
                        to="questions.questao",
                    ),
                ),
                (
                    "resultado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalhes",
                        to="questions.resultado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalhe de Resposta",
                "verbose_name_plural": "Detalhes de Respostas",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="VersaoGabarito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "versao_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="ID único da versão do gabarito",
                        unique=True,
                    ),
                ),
                (
                    "gabaritos_gerados",
                    models.JSONField(
                        help_text="Armazena as informações de embaralhamento das 5 versões"
                    ),
                ),
                ("data_geracao", models.DateTimeField(auto_now_add=True)),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações sobre esta versão do gabarito",
                    ),
                ),
                (
                    "total_questoes",
                    models.IntegerField(
                        default=0, help_text="Número total de questões nesta versão"
                    ),
                ),
                (
                    "simulado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes_gabarito",
                        to="questions.simulado",
                    ),
                ),
                (
                    "usuario_geracao",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que gerou esta versão",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão do Gabarito",
                "verbose_name_plural": "Versões dos Gabaritos",
                "ordering": ["-data_geracao"],
            },
        ),
        migrations.AddField(
            model_name="resultado",
            name="versao_gabarito",
            field=models.ForeignKey(
                blank=True,
                help_text="Versão do gabarito usada na correção",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to="questions.versaogabarito",
            ),
        ),
        migrations.AddField(
            model_name="simulado",
            name="versao_gabarito_oficial",
            field=models.ForeignKey(
                blank=True,
                help_text="Versão do gabarito definida como oficial para correção",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="simulado_oficial",
                to="questions.versaogabarito",
            ),
        ),
    ]
