# Generated by Django 5.2.1 on 2025-07-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0010_remove_simulado_gabaritos_gerados_resultado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulado",
            name="pontuacao_total",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Quanto vale este simulado (número inteiro positivo)",
            ),
        ),
    ]
