# Generated by Django 5.2.1 on 2025-08-23 00:20

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0011_simulado_pontuacao_total"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalhesresposta",
            name="questao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions_detalhes_resposta",
                to="questions.questao",
            ),
        ),
        migrations.AlterField(
            model_name="simulado",
            name="questoes",
            field=models.ManyToManyField(
                blank=True,
                related_name="simulados",
                through="questions.QuestaoSimulado",
                to="questions.questao",
            ),
        ),
        migrations.CreateModel(
            name="QuestaoGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disciplina", models.CharField(max_length=100)),
                ("conteudo", models.CharField(max_length=100)),
                ("enunciado", ckeditor.fields.RichTextField()),
                ("alternativa_a", ckeditor.fields.RichTextField()),
                ("alternativa_b", ckeditor.fields.RichTextField()),
                ("alternativa_c", ckeditor.fields.RichTextField()),
                ("alternativa_d", ckeditor.fields.RichTextField()),
                ("alternativa_e", ckeditor.fields.RichTextField()),
                (
                    "resposta_correta",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "nivel_dificuldade",
                    models.CharField(
                        choices=[("F", "Fácil"), ("M", "Médio"), ("D", "Difícil")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ultima_modificacao", models.DateTimeField(auto_now=True)),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        help_text="Imagens devem ter no máximo 5MB",
                        null=True,
                        upload_to="questoes_globais/",
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(
                        default=True, help_text="Se a questão está disponível para uso"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags separadas por vírgula para facilitar busca",
                        max_length=500,
                    ),
                ),
                (
                    "codigo_identificacao",
                    models.CharField(
                        blank=True,
                        help_text="Código único para identificação da questão",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "criada_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que criou a questão (apenas para auditoria)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questoes_globais_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Questão Global",
                "verbose_name_plural": "Questões Globais",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.AddField(
            model_name="detalhesresposta",
            name="questao_global",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions_detalhes_resposta_global",
                to="questions.questaoglobal",
            ),
        ),
        migrations.AddField(
            model_name="questao",
            name="questao_global_origem",
            field=models.ForeignKey(
                blank=True,
                help_text="Questão global da qual esta foi copiada/adaptada",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questoes_derivadas",
                to="questions.questaoglobal",
            ),
        ),
        migrations.CreateModel(
            name="QuestaoGlobalSimulado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField()),
                (
                    "questao_global",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.questaoglobal",
                    ),
                ),
                (
                    "simulado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.simulado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questão Global do Simulado",
                "verbose_name_plural": "Questões Globais do Simulado",
                "ordering": ["ordem"],
            },
        ),
        migrations.AddField(
            model_name="simulado",
            name="questoes_globais",
            field=models.ManyToManyField(
                blank=True,
                related_name="simulados",
                through="questions.QuestaoGlobalSimulado",
                to="questions.questaoglobal",
            ),
        ),
        migrations.AddIndex(
            model_name="questaoglobal",
            index=models.Index(
                fields=["disciplina", "conteudo"], name="questions_q_discipl_22b291_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questaoglobal",
            index=models.Index(
                fields=["nivel_dificuldade"], name="questions_q_nivel_d_e5db53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questaoglobal",
            index=models.Index(fields=["ativa"], name="questions_q_ativa_be66e8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="questaoglobalsimulado",
            unique_together={("simulado", "ordem"), ("simulado", "questao_global")},
        ),
    ]
