# Generated by Django 5.2.1 on 2025-08-23 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0012_alter_detalhesresposta_questao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questaoglobalsimulado",
            name="questao_global",
        ),
        migrations.RemoveField(
            model_name="questao",
            name="questao_global_origem",
        ),
        migrations.RemoveField(
            model_name="detalhesresposta",
            name="questao_global",
        ),
        migrations.RemoveField(
            model_name="simulado",
            name="questoes_globais",
        ),
        migrations.AlterUniqueTogether(
            name="questaoglobalsimulado",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="questaoglobalsimulado",
            name="simulado",
        ),
        migrations.AlterField(
            model_name="detalhesresposta",
            name="questao",
            field=models.ForeignKey(
                default=539,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions_detalhes_resposta",
                to="questions.questao",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="simulado",
            name="questoes",
            field=models.ManyToManyField(
                related_name="simulados",
                through="questions.QuestaoSimulado",
                to="questions.questao",
            ),
        ),
        migrations.DeleteModel(
            name="QuestaoGlobal",
        ),
        migrations.DeleteModel(
            name="QuestaoGlobalSimulado",
        ),
    ]
