# Generated by Django 5.2.1 on 2025-08-28 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0014_fix_questao_global_cleanup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="questao",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="questao",
            index=models.Index(
                fields=["professor"], name="questions_q_profess_dc69a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questao",
            index=models.Index(
                fields=["disciplina"], name="questions_q_discipl_893e20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questao",
            index=models.Index(
                fields=["nivel_dificuldade"], name="questions_q_nivel_d_4575b5_idx"
            ),
        ),
    ]
