# Generated by Django 5.2.1 on 2025-08-28 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0015_alter_questao_professor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questao",
            name="questao_publica_original",
            field=models.ForeignKey(
                blank=True,
                help_text="Questão pública original da qual esta é uma cópia personalizada",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copias_personalizadas",
                to="questions.questao",
            ),
        ),
    ]
