# Generated by Django 5.2 on 2025-05-01 16:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_user_student_user_and_more'),
        ('questions', '0002_simulado_classes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id', 'name'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='class',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='students', to='classes.class', verbose_name='Turmas'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(verbose_name='Número de matrícula'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_option', models.CharField(max_length=1, verbose_name='Alternativa escolhida')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Está correta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='questions.questaosimulado')),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='questions.simulado')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classes.student')),
            ],
            options={
                'verbose_name': 'Resposta do aluno',
                'verbose_name_plural': 'Respostas dos alunos',
                'unique_together': {('student', 'question', 'simulado')},
            },
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Respostas corretas')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total de questões')),
                ('date_taken', models.DateTimeField(auto_now_add=True, verbose_name='Data de realização')),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='questions.simulado')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='classes.student')),
            ],
            options={
                'verbose_name': 'Desempenho do aluno',
                'verbose_name_plural': 'Desempenhos dos alunos',
                'unique_together': {('student', 'simulado')},
            },
        ),
    ]
