# Generated by Django 5.2 on 2025-05-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_student_options_student_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='versao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Versão do simulado'),
        ),
    ]
