# Generated by Django 5.2.1 on 2025-10-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0004_studentperformance_versao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
            },
        ),
        migrations.AddField(
            model_name="class",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordem"),
        ),
    ]
