# Generated by Django 5.2.1 on 2025-10-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0005_alter_class_options_class_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="data_nascimento",
            field=models.DateField(
                blank=True,
                help_text="Formato: DD/MM/AAAA",
                null=True,
                verbose_name="Data de Nascimento",
            ),
        ),
    ]
