# Generated by Django 5.2.1 on 2025-07-03 00:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompraCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_token",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="Token de Compra"
                    ),
                ),
                (
                    "produto_id",
                    models.CharField(max_length=100, verbose_name="ID do Produto"),
                ),
                (
                    "quantidade_creditos",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade de Créditos",
                    ),
                ),
                (
                    "data_compra",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Compra"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "validada_google",
                    models.BooleanField(
                        default=False, verbose_name="Validada pelo Google"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras_credito",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra de Crédito",
                "verbose_name_plural": "Compras de Créditos",
                "db_table": "creditos_compracredito",
                "ordering": ["-data_compra"],
            },
        ),
        migrations.CreateModel(
            name="CreditoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_creditos",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total de Créditos",
                    ),
                ),
                (
                    "usados_creditos",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Créditos Utilizados",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credito_usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crédito do Usuário",
                "verbose_name_plural": "Créditos dos Usuários",
                "db_table": "creditos_creditousuario",
            },
        ),
    ]
